language: python
addons:
  apt:
    packages:
    - verilator
python:
    - "3.6"

install:
    # Convenience script for installing coreir on travis
    # - wget https://raw.githubusercontent.com/phanrahan/magma/master/.travis/install_coreir.sh
    # - source install_coreir.sh
    #- wget https://github.com/rdaly525/coreir/releases/download/v0.0.12/coreir.tar.gz
    #- mkdir coreir_release;
    #- tar -xf coreir.tar.gz -C coreir_release --strip-components 1;
    #- export PATH=$TRAVIS_BUILD_DIR/coreir_release/bin:$PATH;
    #- export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/coreir_release/lib:$LD_LIBRARY_PATH;
    - pip install -r requirements.txt
    - pip install python-coveralls
    - pip install pytest-cov pytest-pep8
    - pip install -e .

    - export PYTHONPATH=.:$PYTHONPATH

script:
    - pytest --cov bit1 -v  --cov-report term-missing tests

after_success:
    - coveralls
